### ISSUE TITLE
problem with dummy.yml

### ISSUE THREAD

**Issue by cfregly** [viafoura/deprecated-buri#29]
ERROR: /home/vagrant/buri/playbooks/vars/dummy.yml must be stored as a dictionary/hash

ubuntu 12.04

**Comment by jhohertz** [comment]
That file exists solely because Ansible can't load a file only if it exists, so we instead do a "load first in list", with the file we want to load at the front of the list, and the dummy at the back.

It seems versions of Ansible, pre 1.6 I think, don't like empty variable files, so I've added a dummy var to the dummy file for now.

All this is probably going away once I do the final rework on variable loading.

**Comment by cfregly** [comment]
ah my bad.  yeah, my vagrant VM was on ansible 1.4.4.  just upgraded to ansible 1.6.10.

**Comment by jhohertz** [comment]
Cool. I had been trying to support 1.4+, and in theory this item is worked around, but in closing it, since you're up to 1.6, and there's some stuff in 1.6+ only I want to use, I am going to make it a hard requirement going forward, README updated to reflect that, steering people to pip install.

Closing.
